'depth': 10
'min_density': 0.1
'n_threads': -1
'downsample': False
'voxel_size': 0.4 #0.4
'max_nn': 20
'pc_range':  [-40, -40, -3, 40, 40, 3.4]
'occ_size':  [200, 200, 16]
'self_range': [3.0, 3.0, 3.0]